mybatis:
  type-aliases-package: com.example.demo.model
  type-handlers-package: com.example.typehandler
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
spring:
  datasource:
    url: jdbc:mysql://localhost/oauth?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  session:
    store-type: None
server:
  servlet:
    session:
      timeout: 3000
project:
  settings:
    oauth:
      secretKey: 123456